# This is a basic workflow to help you get started with Actions

name: Pandoc

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://pandoc/core:2.9
        with:
          args: >-
            -o output/releasedmethod.docx
            --reference-doc=reference.docx
            -t docx
            title.txt 
            README.md 
            CODE_OF_CONDUCT.md 
            CONTRIBUTING.md 
            introduction.md 
            why.md 
            pillars.md 
            management-reporting.md 
            software-planning.md 
            testing-qa.md 
            release-management.md 
            documentation.md 
            sales-kit.md 
            saleskit/sales-presentations.md 
            saleskit/proposal-template.md 
            saleskit/brochure.md 
            saleskit/datasheet.md 
            saleskit/sales-battlecard.md 
            saleskit/web-site.md 
            startup-checklist.md 
            corporate.setup.md 
            team-model.md 
            usefulresources.md 
            glossary.md 
            whitepaper-crmme.io.md
      - uses: actions.upload-artifact@master
        with:
          name: output
          path: output
